name: Deploy to Cloudflare R2

# 當推送到 main 分支時觸發
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to R2

    steps:
      # 步驟 1: Checkout 您的程式碼
      - name: Checkout
        uses: actions/checkout@v4

      # 步驟 2: 使用新的官方 rclone-action
      - name: Sync files to Cloudflare R2
        # 【已修正】更換為 rclone 官方的 Action
        uses: rclone/rclone-action@v1
        with:
          # args 保持不變，依然是您要執行的 rclone 指令
          args: 'sync ./public twroz-r2:twroz-assets --progress'
        env:
          # 【已修正】將所有設定移至 env 環境變數區塊
          # 語法為 RCLONE_CONFIG_[遠端名稱]_[參數]
          RCLONE_CONFIG_TWROZ_R2_TYPE: "s3"
          RCLONE_CONFIG_TWROZ_R2_PROVIDER: "Cloudflare"
          RCLONE_CONFIG_TWROZ_R2_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          RCLONE_CONFIG_TWROZ_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_TWROZ_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}