name: Deploy to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to R2

    steps:
      # 步驟 1: Checkout 您的程式碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 步驟 2: 安裝 Rclone
      # 【已修正】更換為您提供的 AnimMouse/setup-rclone Action
      # 我們不需要提供 rclone_config，因為我們將使用環境變數進行無設定檔操作
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1.2.0 # 使用一個明確的、最新的版本號

      # 步驟 3: 執行 Rclone 同步指令
      # rclone 已被上一步安裝好，現在我們直接執行指令
      - name: Sync files to Cloudflare R2
        run: rclone sync ./public twroz-r2:twroz-assets --progress
        env:
          # 【保持不變】這些環境變數的格式是 rclone 的標準，可以直接被使用
          # rclone 會自動讀取它們來設定一個名為 twroz-r2 的遠端
          RCLONE_CONFIG_TWROZ_R2_TYPE: "s3"
          RCLONE_CONFIG_TWROZ_R2_PROVIDER: "Cloudflare"
          RCLONE_CONFIG_TWROZ_R2_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          RCLONE_CONFIG_TWROZ_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_TWROZ_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}